- platform: generic
  name: Living Room Camera
  still_image_url: !secret living_room_camera_still_image_url
  stream_source: !secret living_room_camera_stream_source
  username: !secret living_room_camera_username
  password: !secret living_room_camera_password
  authentication: digest
  verify_ssl: false

- platform: generic
  name: Lower Floor Camera
  still_image_url: !secret lower_floor_camera_still_image_url
  stream_source: !secret lower_floor_camera_stream_source
  username: !secret lower_floor_camera_username
  password: !secret lower_floor_camera_password
  authentication: digest
  verify_ssl: false

- platform: mjpeg
  name: OctoPrint
  still_image_url: !secret octoprint_still_image_url
  mjpeg_url: !secret octoprint_mjpeg_url
