include:
  domains:
  entities:
    - alarm_control_panel.home_alarm
    - binary_sensor.back_door_contact
    - binary_sensor.front_door_contact
    - binary_sensor.master_bedroom_pir_sensor_occupancy
    - light.lamp_1
    - light.lamp_2
    - light.lamp_3
    - light.lamp_4
    - light.lamp_5
    - light.lamp_6
    - light.lamp_7
    - light.lamp_8
    - media_player.lg_smart_tv
    - person.joana
    - person.pedro
    - sensor.kids_bedroom_climate_humidity
    - sensor.kids_bedroom_climate_temperature
    - sensor.living_room_climate_humidity
    - sensor.living_room_climate_temperature
    - sensor.lower_floor_climate_humidity
    - sensor.lower_floor_climate_temperature
    - sensor.master_bedroom_climate_humidity
    - sensor.master_bedroom_climate_temperature
    - sensor.smart_vibration_sensor_action
    - switch.living_room_smart_plug
    - switch.lower_floor_smart_plug
    - switch.kids_bedroom_smart_plug
    - switch.washing_machine_smart_plug
    - switch.master_bedroom_smart_plug
