title: Lights
path: lights
icon: mdi:lightbulb-outline
cards:
  - type: entities
    title: Living Room
    show_header_toggle: false
    entities:
      - entity: light.lamp_1
      - entity: light.lamp_2
      - entity: light.lamp_3
      - entity: light.kids_corner_group
        name: Kids Corner
      - entity: light.lamp_7
        name: Desk lamp
      - entity: light.elgato_key_light_air
        name: Desk camera lamp

  - type: entities
    title: Master Bedroom
    show_header_toggle: false
    entities:
      - entity: light.master_bedroom_dimmer
        name: Ceiling dimmer
      - entity: light.lamp_4
      - entity: light.lamp_8
        name: Desk lamp

  - type: entities
    title: Kids Bedroom
    show_header_toggle: false
    entities:
      - entity: light.kids_bedroom_dimmer
        name: Ceiling dimmer
