slate:
  # Main colors
  primary-color: '#2980b9'
  accent-color: '#b58e31'
  dark-primary-color: '#2980b9'
  light-primary-color: '#2980b9'
  # Text colors
  primary-text-color: '#FFFFFF'
  text-primary-color: 'var(--primary-text-color)'
  secondary-text-color: '#b58e31'
  disabled-text-color: '#777777'
  label-badge-border-color: 'green'
  # Sidebar
  sidebar-icon-color: '#777777'
  # Background colors
  primary-background-color: '#222222'
  secondary-background-color: '#222222'
  divider-color: 'rgba(0, 0, 0, .12)'
  table-row-background-color: '#292929'
  table-row-alternative-background-color: '#292929'
  # Nav Menu
  paper-listbox-color: '#777777'
  paper-listbox-background-color: '#141414'
  paper-grey-50: 'var(--primary-text-color)'
  paper-grey-200: '#222222'
  # Paper card
  paper-card-header-color: '#2980b9'
  paper-card-background-color: '#292929'
  paper-dialog-background-color: '#292929'
  paper-item-icon-color: 'var(--primary-text-color)'
  paper-item-icon-active-color: '#b58e31'
  paper-item-icon_-_color: 'green'
  paper-item-selected_-_background-color: '#292929'
  paper-tabs-selection-bar-color: 'green'
  # Labels
  label-badge-red: 'var(--primary-color)'
  label-badge-text-color: 'var(--primary-text-color)'
  label-badge-background-color: '#222222'
  # Switches
  paper-toggle-button-checked-button-color: '#2980b9'
  paper-toggle-button-checked-bar-color: '#2980b9'
  paper-toggle-button-checked-ink-color: '#2980b9'
  paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
  # Sliders
  paper-slider-knob-color: '#2980b9'
  paper-slider-knob-start-color: '#2980b9'
  paper-slider-pin-color: '#2980b9'
  paper-slider-active-color: '#2980b9'
  paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
  paper-slider-secondary-color: 'var(--secondary-background-color)'
  paper-slider-disabled-active-color: 'var(--disabled-text-color)'
  paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
  # Google colors
  google-red-500: '#b93829'
  google-green-500: '#2980b9'
  # Changes to fix history/logbook menus
  lumo-primary-text-color: '#2980b9'
  lumo-secondary-text-color: '#2980b9'
  lumo-primary-color: '#2980b9'
  # Calendar day numbers
  lumo-body-text-color: '#b58e31'
  # Calendar/Date-Picker Background
  lumo-base-color: '#222222'
  # Month/Year header
  lumo-header-text-color: 'var(--lumo-body-text-color)'
  # DayOfWeek Header
  lumo-tertiary-text-color: 'var(--lumo-body-text-color)'
  lumo-shade: '#222222'
  lumo-shade-90pct: 'rgba(34, 34, 34, .9)'
  lumo-shade-80pct: 'rgba(34, 34, 34, .8)'
  lumo-shade-70pct: 'rgba(34, 34, 34, .7)'
  lumo-shade-60pct: 'rgba(34, 34, 34, .6)'
  lumo-shade-50pct: 'rgba(34, 34, 34, .5)'
  lumo-shade-40pct: 'rgba(34, 34, 34, .4)'
  lumo-shade-30pct: 'rgba(34, 34, 34, .3)'
  lumo-shade-20pct: 'rgba(34, 34, 34, .2)'
  lumo-shade-10pct: 'rgba(34, 34, 34, .1)'
  lumo-shade-5pct: 'rgba(34, 34, 34, .05)'
  lumo-tint-5pct: '#222222'
  # fix for device configuration screen
  card-background-color: "var(--paper-card-background-color)"

Dark - Gray:
  ### Main Interface Colors ###
  primary-color: "#A3A3A3"
  light-primary-color: "#C5C5C5"
  primary-background-color: "#272727"
  secondary-background-color: var(--primary-background-color)
  divider-color: "#343434"
  ### Text ###
  primary-text-color: "#FFFFFD"
  secondary-text-color: "#87BF50"
  text-primary-color: "#FFFFFF"
  disabled-text-color: "#A3A3A3"
  ### Sidebar Menu ###
  sidebar-icon-color: "#A3A3A3"
  sidebar-text-color: "#FFFFFD"
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#87BF50"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color)
  ### States and Badges ###
  state-icon-color: "#87BF50"
  state-icon-active-color: "#F7AA1C"
  state-icon-unavailable-color: var(--disabled-text-color)
  ### Sliders ###
  paper-slider-knob-color: "#87BF50"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  ### Labels ###
  label-badge-background-color: "#575757"
  label-badge-text-color: "#FFFFFD"
  label-badge-red: "#575757"
  ### Cards ###
  paper-card-background-color: "#2D2D2D"
  paper-listbox-background-color: var(--primary-background-color)
  ### Toggles ###
  paper-toggle-button-checked-button-color: "#87BF50"
  paper-toggle-button-checked-bar-color: "#598330"
  paper-toggle-button-unchecked-button-color: "#A3A3A3"
  paper-toggle-button-unchecked-bar-color: "#6F6F6F"
  ### Table row ###
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)

Dark - Green:
  ### Main Interface Colors ###
  primary-color: "#03B14B"
  light-primary-color: "#47FC92"
  primary-background-color: "#1F1F28"
  secondary-background-color: var(--primary-background-color)
  divider-color: "#2F2F3D"
  ### Text ###
  primary-text-color: "#FFFFFF"
  secondary-text-color: "#47FC92"
  text-primary-color: "#FFFFFF"
  disabled-text-color: "#464653"
  ### Sidebar Menu ###
  sidebar-icon-color: "#B6B6C1"
  sidebar-text-color: "#F1F1F1"
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#47FC92"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color)
  ### States and Badges ###
  state-icon-color: "#04E762"
  state-icon-active-color: "#FBD150"
  state-icon-unavailable-color: var(--disabled-text-color)
  ### Sliders ###
  paper-slider-knob-color: "#04E762"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  ### Labels ###
  label-badge-background-color: "#464653"
  label-badge-text-color: "#FFFFFF"
  label-badge-red: "#343443"
  ### Cards ###
  paper-card-background-color: "#23232E"
  paper-listbox-background-color: var(--primary-background-color)
  ### Toggles ###
  paper-toggle-button-checked-button-color: "#04E762"
  paper-toggle-button-checked-bar-color: "#47FC92"
  paper-toggle-button-unchecked-button-color: var(--paper-toggle-button-checked-button-color)
  paper-toggle-button-unchecked-bar-color: "#343443"
  ### Table row ###
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)

midnight:
  # Main colors
  primary-color: '#5294E2'                                                        # Header
  accent-color: '#E45E65'                                                         # Accent color
  dark-primary-color: 'var(--accent-color)'                                       # Hyperlinks
  light-primary-color: 'var(--accent-color)'                                      # Horizontal line in about

  # Text colors
  primary-text-color: '#FFFFFF'                                                   # Primary text colour, here is referencing dark-primary-color
  text-primary-color: 'var(--primary-text-color)'                                 # Primary text colour
  secondary-text-color: '#5294E2'                                                 # For secondary titles in more info boxes etc.
  disabled-text-color: '#7F848E'                                                  # Disabled text colour
  label-badge-border-color: 'green'                                               # Label badge border, just a reference value

  # Background colors
  primary-background-color: '#383C45'                                             # Settings background
  secondary-background-color: '#383C45'                                           # Main card UI background
  divider-color: 'rgba(0, 0, 0, .12)'                                             # Divider

  # Table rows
  table-row-background-color: '#353840'                                           # Table row
  table-row-alternative-background-color: '#3E424B'                               # Table row alternative

  # Nav Menu
  paper-listbox-color: 'var(--primary-color)'                                     # Navigation menu selection hoover
  paper-listbox-background-color: '#2E333A'                                       # Navigation menu background
  paper-grey-50: 'var(--primary-text-color)'
  paper-grey-200: '#414A59'                                                       # Navigation menu selection

  # Paper card
  paper-card-header-color: 'var(--accent-color)'                                  # Card header text colour
  paper-card-background-color: '#434954'                                          # Card background colour
  paper-dialog-background-color: '#434954'                                        # Card dialog background colour
  paper-item-icon-color: 'var(--primary-text-color)'                              # Icon color
  paper-item-icon-active-color: '#F9C536'                                         # Icon color active
  paper-item-icon_-_color: 'green'
  paper-item-selected_-_background-color: '#434954'                               # Popup item select
  paper-tabs-selection-bar-color: 'green'

  # Labels
  label-badge-red: 'var(--accent-color)'                                          # References the brand colour label badge border
  label-badge-text-color: 'var(--primary-text-color)'                             # Now same as label badge border but that's a matter of taste
  label-badge-background-color: '#2E333A'                                         # Same, but can also be set to transparent here

  # Switches
  paper-toggle-button-checked-button-color: 'var(--accent-color)'
  paper-toggle-button-checked-bar-color: 'var(--accent-color)'
  paper-toggle-button-checked-ink-color: 'var(--accent-color)'
  paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'

  # Sliders
  paper-slider-knob-color: 'var(--accent-color)'
  paper-slider-knob-start-color: 'var(--accent-color)'
  paper-slider-pin-color: 'var(--accent-color)'
  paper-slider-active-color: 'var(--accent-color)'
  paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
  paper-slider-secondary-color: 'var(--secondary-background-color)'
  paper-slider-disabled-active-color: 'var(--disabled-text-color)'
  paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'

  # Google colors
  google-red-500: '#E45E65'
  google-green-500: '#39E949'

#test:
#  primary-color: '#D4D4D4'
#  accent-color: '#CCCCCC'
#  dark-primary-color: '#D4D4D4'
#  light-primary-color: '#D4D4D4'
#
#  primary-background-color: '#1E1E1E'
#  secondary-background-color: '#252526'
